server:
  port: 30030
spring:
  datasource:
    url:  jdbc:postgresql://dpg-d1a85i3e5dus73ebpp7g-a.frankfurt-postgres.render.com:5432/collaborationsm
    username: martin
    password: 262MAhsztz0mR9RvPOQBqMeM29w5t1a0
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:  none
      format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace
jwt:
  secret: xlJQSlmC4lT8HPtBY6vCf07klWfhUMmQze
  expiration: 36000000
